### ISSUE TITLE
DCR Physics: don't need Rx in Fig 64

### ISSUE THREAD

**Issue by yangdikun** [ubcgif/em#262]
I don't see the need to plot and mention Rx or data for the two-sphere problem (Fig 64), as we are not showing any data here. Only the source matters.

![capture](https://cloud.githubusercontent.com/assets/5066933/17953137/a8a07984-6a25-11e6-825a-ee410d2c1e2a.PNG)

**Comment by sdevriese** [comment]
@fourndo ?

**Comment by lheagy** [comment]
Since we make connections to the measurement of responses in the html radio button widget at the top of the page, I don't think it is necessary to remove the receivers. Although they may not be used on this specific page, this example is referred to later on in the dcr section, and the receivers are used. So here, they serve to set some context. Thoughts @dougoldenburg , @fourndo ?

**Comment by fourndo** [comment]
That's right, it was to make the connection with the next pages and give a sense of scale. Otherwise it's a pretty boring figure

**Comment by lheagy** [comment]
@yangdikun, @fourndo : I will leave it up to you guys to decide on this. please close the issue once it has been resolved. Thanks!
