### ISSUE TITLE
Current web layout difficult to navigate

### ISSUE THREAD

**Issue by yangdikun** [ubcgif/em#284]
Some of us have the feeling that the current layout (blue bar on the top with drop-down menu and left/right arrows) is not easy to use. In particular:
- One a leaf page, users don't know where they are on the big map. I am now relying on the web address, which reflects the hierarchy, but a newcomer can easily get lost.
- For example,  if I am on Electrical Conductivity > Tables of value, getting to the same table for permittivity needs a lot of clicks involving using the root drop-down menu again or many "previous chapter".
- The "previous chapter" button on each index page doesn't make sense, since an index (landing) page is the first page of a particular topic. It may incorrectly remind people that the index page is preluded by another page.
- Another fact that makes the navigation even more difficult is there are as many as 7 levels in the structure.

I think the essential problem is the drop-down menu is only for the first level, and the individual pages only show local information about the structure. It's not easy to access the middle levels. Those issues are not really bothering me, but may cause troubles for new users.

We can discuss.

**Comment by thast** [comment]
Also, Do we want to put some thoughts about the organisation of Maxwell Fundamental? Few examples:

It is indeed not clear where to look to find the dipoles for example. They are right now in Maxwell Equation/Maxwell’s Equations in Homogeneous Media (so there are not referred as dipole). But there is also a section Analytic in Solving Maxwell Equation.
-The section Quick Guide to Maxwell’s Equations would do a great introduction page to the Maxwell's equation section in my opinion. It seems light compared to other same-level sections. Does it deserve its very own category in the index?

@lheagy @yangdikun @dougoldenburg : some thoughts about it?

**Comment by lheagy** [comment]
- Agreed, the navigation is tricky. I have been searching for ways to adapt the sidebar so that it gives you all of the contents for the current "chapter" you are in, but have not yet figured this out. I think this would resolve most of your points (the ability to get a global perspective of the chapter without getting lost in the entire site. If others are willing to help me search for a solution, that would be huge! I have been starting mainly from the [sphinx documentation](http://www.sphinx-doc.org/en/stable/) and the [sphinx bootstrap theme](https://ryan-roemer.github.io/sphinx-bootstrap-theme/). 
- One other method for helping with navigation is the appropriate use of internal links. For the example you gave with the table of electrical conductivity values, perhaps it would be beneficial to include a statement on that page along the lines of (I made up the references, they will need to be double-checked) 
```
Similar tables are available for the other relevant physical properties :ref:`magnetic permeability <magnetic_permeability_table_of_values> and :ref:`dielectric permittivity <dielectric_permittivity_table_of_values>`
```

- @yangdikun, I am not sure what you mean by "leaf-page", but there is a Site Map, accessible in the footer and at the bottom of the contents that was added in #213 
![image](https://cloud.githubusercontent.com/assets/6361812/18232678/d1b6be2a-7289-11e6-8e30-0779239401ea.png)

@thast : I have moved your comment to issue #285 as it raises separate discussion points.

**Comment by yangdikun** [comment]
@lheagy Thanks for the explaining and constant improvement. I think the "Site Map" can solve a lot of navigating problems for now. Something we may want to keep on the list for the next iteration of refinement:
(1) The fully expanded site map is a bit long as a navigating tool. (I know it is what a site map is supposed to be)
(2) Not sure how intuitive for people to resort to Site Map if they are at "vector potentials" and want to go two levels up. 

Maybe we can discuss this problem at the weekly meeting. @dougoldenburg

**Comment by rowanc1** [comment]
Another possible solution is something more interactive. It would be super helpful to see what currently is and is not under-construction. Possibly to see thumbnails of images, tooltips for which modules are math heavy or have an interactive notebook etc.

Something to build on could be here:
https://bl.ocks.org/mbostock/4339083

Or a force-directed graph (probably less useful as a navigation tool, but more useful for seeing links):
http://bl.ocks.org/MoritzStefaner/1377729

I talked briefly about this with @lheagy, there are a few things that either of us could do to highlight some more of the work to people from the very start.

**Comment by lheagy** [comment]
👍 on the [collapsible tree](https://bl.ocks.org/mbostock/4339083) as a navigation tool! Another suggestion @rowanc1 raised is to color the nodes by ready (green) and under construction (amber?). This would set expectations for the page you are navigating to (instead of blindly navigating to a bunch of incomplete pages) 

The force directed graph will be a valuable tool for looking at links (and for us identifying links, and gaps where there should be links), but it likely less urgent at this stage.

**Comment by rowanc1** [comment]
I have completed an initial prototype, I will clean it up and open a pull request in the next few days.

![outline-view](https://cloud.githubusercontent.com/assets/913249/18407594/fdc0c12a-76c9-11e6-878b-cb54c1bc08a1.gif)

**Comment by lheagy** [comment]
Having a read-the-docs style collapsible sidebar would also be very helpful for keeping track of where you are at any point

![image](https://cloud.githubusercontent.com/assets/6361812/18732572/079cd5aa-8019-11e6-9fb4-82eaac11fae3.png)

To work with the current theme, we will need to write a custom sidebar which accesses the doctree files

**Comment by lheagy** [comment]
I have launched a version of em geosci using the read-the-docs theme: https://1-dot-emgeosci.appspot.com/ 

There are a few styling things that will need cleanup (eg adding back the "edit on github button", adding the creative commons license to the footer, styling on the autodoc'ed pages). These are minor though and can be implemented before making a transition.  

Please have a look and see what you think! We can make a decision at the meeting next week. 

![image](https://cloud.githubusercontent.com/assets/6361812/18963409/ba580bc2-8629-11e6-8bbb-afb5b197d782.png)

**Comment by fourndo** [comment]
I think it looks great.  I personally don't care too much if the equation number is on top, and i m sure Lindsey will find us a hack to bring it down at some point ;)

**Comment by dougoldenburg** [comment]
No contest! The ease of navigation and knowing where you are is far superior. The equation numbering is annoying but not a show-stopper.

**Comment by lheagy** [comment]
I am going to close this for now with #322. We can re-open a separate issue for interactive visualizations
